### PR TITLE
Constants for op values; pass operation duration to logger

### PR DESCRIPTION
**Pull request by dcormier**

### CODE REVIEW

**Comment by dcormier** [comment]
That's the fastest I've ever had a PR approved for a repo where I had no prior contact with the maintainer. Thanks for being so responsive, @luna-duclos.

**Comment by luna-duclos** [comment]
Looking good, thanks for your contribution!

**Comment by luna-duclos** [comment]
> That's the fastest I've ever had a PR approved for a repo where I had no prior contact with the maintainer. Thanks for being so responsive, @luna-duclos.

No problem! :) Feel free to merge it at will

**Comment by dcormier** [comment]
>Feel free to merge it at will

I don't have permissions to merge as I'm not a maintainer on the repo. The only option I have is to close the PR.

image

**Comment by luna-duclos** [comment]
I assumed github would let you merge after my approval, guess not, merging this for you then

**Pull request merged**
