### PR TITLE
Add support for Connector interface

### PR DESCRIPTION
**Pull request by iheanyi**
When you try to use this package with more modern versions of Go that use the [`Connector`](https://godoc.org/database/sql/driver#Connector) interface, they don't play nicely together. This PR fixes that.

### CODE REVIEW

**Comment by dolmen** [comment]
This change should be isolated with build tags to allow backward compatibility with Go versions that don't have the Connector interface.

**Comment by dolmen** [comment]
@iheanyi ping

**Comment by iheanyi** [comment]
@dolmen Apologies, lost track of this. Which versions should this be pinned this to?

**Comment by iheanyi** [comment]
@dolmen I've moved these to an external `connector.go` file and added a build tag, can you please take another look at this when you get the chance? Thanks!

**Comment by luna-duclos** [comment]
LGTM! Merging, thank you! :)

**Pull request merged**
